<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "subhh_oa_dashboard"
 *
 * Auto generated by Extension Builder 2019-04-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'SUBHH OA-Dashboard',
    'description' => '',
    'category' => 'plugin',
    'author' => 'eww',
    'author_email' => 'info@effective-webwork.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
